apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-api-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "demo-api"
        track: "canary"
    spec:
      containers:
        - name: "demo-api"
          image: "trescst/demo:v2.0.1"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /version
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /version
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
