apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-api
  name: demo-api
  namespace: default
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-api
  type: NodePort
